FROM node:16

WORKDIR /app

COPY ./package.json ./package.json
COPY ./public ./public
COPY ./src ./src
COPY ./.env ./.env

ENV PATH /app/node_modules/.bin:$PATH

RUN npm install

EXPOSE 3000

CMD ["npm", "start"]